### ISSUE TITLE
Build script?

### ISSUE THREAD

**Issue by samuelh2005** [MCJack123/craftos-efi#1]
can you make one please

**Comment by ghost** [comment]
go to releases page, believe me its a easier way

**Comment by MCJack123** [comment]
No.

----

EDK II is a *pain* to build for, and you have to set up all sorts of toolchains to get it up and running. In fact, they have you use their own `build` program to build projects. My suggestion is to read [Getting Started with EDK II](https://github.com/tianocore/tianocore.github.io/wiki/Getting-Started-with-EDK-II) and [Getting Started Writing Simple Application](https://github.com/tianocore/tianocore.github.io/wiki/Getting-Started-Writing-Simple-Application) for more info on how to get it set up. Once done, you can clone this repo into the main EDK II build tree, and run `build -p craftos-efi/CraftOSPkg.dsc`. I can't guarantee it'll work, but if the stars align it just might.

If you just want a built version, head over to the [releases](https://github.com/MCJack123/craftos-efi/releases) page, where a binary for the latest commit is available (I haven't made any changes since then). If you need an image file, you can just drop the `CCEFI.efi` file into the ESP of the image (it's the first partition, FAT32), and adjust `startup.nsh` to point to `CCEFI` instead of `CraftOS`.

**Comment by Kuberow** [comment]
it more fun to make a custom build tho so i reccomend adding a build script
